name: hans
channels:
  - bokeh
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - alembic=1.4.2=py_0
  - asn1crypto=1.3.0=py38_0
  - astroid=2.3.3=py38_0
  - async_generator=1.10=py_0
  - attrs=19.3.0=py_0
  - autopep8=1.4.4=py_0
  - backcall=0.1.0=py38_0
  - beautifulsoup4=4.9.0=py38_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - blinker=1.4=py38_0
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py38h32f6830_0
  - certipy=0.1.3=py_0
  - cffi=1.14.0=py38h2e261b9_0
  - chardet=3.0.4=py38_1003
  - configurable-http-proxy=4.0.1=node6_0
  - cryptography=2.8=py38h1ba5d50_0
  - cudatoolkit-dev=10.1.243=h516909a_3
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - flake8=3.7.9=py38_0
  - freetype=2.9.1=h8a8886c_1
  - future=0.18.2=py38_0
  - gmp=6.1.2=h6c8ec71_1
  - idna=2.9=py_1
  - importlib_metadata=1.5.0=py38_0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py38h39e3cac_0
  - ipython=7.13.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py38_0
  - jedi=0.15.2=py38_0
  - jinja2=2.11.1=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.4=py_0
  - jsonschema=3.2.0=py38_0
  - jupyter_bokeh=1.1.1=py_0
  - jupyter_client=6.1.2=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterhub=1.0.0=py38_0
  - jupyterlab=1.2.6=pyhf63ae98_0
  - jupyterlab_code_formatter=1.1.0=py_0
  - jupyterlab_server=1.1.0=py_0
  - krb5=1.17.1=h173b8e3_0
  - lazy-object-proxy=1.4.3=py38h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mako=1.1.2=py_0
  - markupsafe=1.1.1=py38h7b6447c_0
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.0=166
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.0.15=py38ha843d7b_0
  - mkl_random=1.1.0=py38h962f231_0
  - mypy_extensions=0.4.3=py38_0
  - nb_conda=2.2.1=py38_2
  - nb_conda_kernels=2.2.3=py38_0
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=he6710b0_0
  - nodejs=6.11.2=h3db8ef7_0
  - notebook=6.0.3=py38_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_0
  - packaging=20.3=py_0
  - pamela=1.0.0=py_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.6.2=py_0
  - pathspec=0.7.0=py_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.0.0=py38hb39fc2d_0
  - pip=20.0.2=py38_1
  - pluggy=0.13.1=py38_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py38_0
  - pycodestyle=2.5.0=py38_0
  - pycparser=2.20=py_0
  - pycurl=7.43.0.5=py38h1ba5d50_0
  - pydocstyle=4.0.1=py_0
  - pyflakes=2.1.1=py38_0
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py38_0
  - pylint=2.4.4=py38_0
  - pyopenssl=19.1.0=py38_0
  - pyparsing=2.4.6=py_0
  - pyrsistent=0.16.0=py38h7b6447c_0
  - pysocks=1.7.1=py38_0
  - python=3.8.2=hcf32534_0
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - python-jsonrpc-server=0.3.4=py_0
  - python-language-server=0.31.10=py38_0
  - python_abi=3.8=1_cp38
  - pyzmq=18.1.1=py38he6710b0_0
  - readline=8.0=h7b6447c_0
  - regex=2020.4.4=py38h7b6447c_0
  - requests=2.23.0=py38_0
  - rope=0.16.0=py_0
  - selenium=3.141.0=py38h7b6447c_1000
  - send2trash=1.5.0=py38_0
  - setuptools=46.1.3=py38_0
  - six=1.14.0=py38_0
  - snowballstemmer=2.0.0=py_0
  - soupsieve=2.0=py_0
  - sqlalchemy=1.3.16=py38h7b6447c_0
  - sqlite=3.31.1=h62c20be_1
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - toml=0.10.0=pyh91ea838_0
  - tornado=6.0.4=py38h7b6447c_1
  - tqdm=4.45.0=py_0
  - traitlets=4.3.3=py38_0
  - typed-ast=1.4.1=py38h7b6447c_0
  - typing_extensions=3.7.4.1=py38_0
  - ujson=1.35=py38h7b6447c_0
  - urllib3=1.25.8=py38_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - wrapt=1.12.1=py38h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - yapf=0.28.0=py_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - aiohttp==3.6.2
    - appdirs==1.4.3
    - async-timeout==3.0.1
    - blurhash==1.1.4
    - bokeh==1.4.0
    - boost==0.1
    - click==7.0
    - cycler==0.10.0
    - dareblopy==0.0.2
    - dlutils==0.0.12
    - fridge==0.2
    - imageio==2.6.1
    - imageio-ffmpeg==0.3.0
    - joblib==0.14.1
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-lsp==0.7.0
    - jupyter-nbextensions-configurator==0.4.1
    - jupyter-server-proxy==1.2.0
    - jupyterlab-bokeh-server==0.2.0
    - jupyterlab-nvdashboard==0.2.0
    - jupyterthemes==0.20.0
    - kiwisolver==1.1.0
    - lesscpy==0.14.0
    - lxml==4.5.0
    - mastodon-py==1.5.1
    - matplotlib==3.1.3
    - mpmath==1.1.0
    - multidict==4.7.4
    - ninja==1.9.0.post1
    - numpy==1.16.6
    - opencv-contrib-python==4.2.0.32
    - opencv-python==4.2.0.32
    - ply==3.11
    - powerlaw==1.4.6
    - protobuf==3.11.3
    - psutil==5.6.7
    - py3nvml==0.2.5
    - pygeocoder==1.2.5
    - pynvml==8.0.4
    - python-magic==0.4.15
    - pytz==2019.3
    - pyyaml==5.3
    - requests-oauthlib==1.3.0
    - s-tui==1.0.0
    - scikit-learn==0.22.2.post1
    - scikit-video==1.1.11
    - scipy==1.4.1
    - seaborn==0.10.1
    - simpervisor==0.3
    - sklearn==0.0
    - torch==1.5.0
    - torchvision==0.6.0
    - twitterapi==2.5.11
    - urwid==2.1.0
    - xmltodict==0.12.0
    - yacs==0.1.7
    - yarl==1.4.2
prefix: /home/hans/.conda/envs/hans

